name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: ./src/PrivatePdfConverter
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore --configuration Release
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Build
        run: dotnet build --no-restore -p:TreatWarningsAsErrors=true
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Test
        run: dotnet test --configuration Release
        working-directory: ./
