name: Deploy .NET Tool to NuGet

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: ./src/PrivatePdfConverter
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Pack as .NET Tool
        run: dotnet pack --configuration Release
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ${{ env.PROJECT_DIR }}/nupkg/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
